[project]
    name = "sprinter"
    version = "0.0.0"
    requires-python = "==3.12.0"
dependencies = [
    "mediapipe>=0.10.14",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "protobuf>=4.25.8",
    "pytest>=9.0.1",
    "torch>=2.9.1",
]
